version: "3"
services:
  flaskr:
    build: .
    ports:
      - "5001:5000"
    container_name: app
    volumes:
      - .:/usr/src
    command: flask --app /usr/src/flaskrapp run --host=0.0.0.0 --debug
